name: Beta CI
on:
  workflow_dispatch:
      inputs:
        ci_upload:
          description: 'Upload to CI channel'
          required: false
          type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  
        with:
          submodules: 'recursive'

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean Gradle Cache
        run: ./gradlew clean

      - name: Build armv8 APK
        run: ./gradlew assembleArmv8Debug

      - name: Build armv7 APK
        run: ./gradlew assembleArmv7Debug

      - name: Build universal APK
        run: ./gradlew assembleallDebug

      - name: Build Version
        run: ./gradlew getVersion

      - name: Set Environment Variables
        id: version-env
        run: | 
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV  
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1

      - name: Rename APK files
        run: |
          mv app/build/outputs/apk/armv8/debug/*.apk app/build/outputs/apk/armv8/debug/snapenhance-${{ env.version }}-armv8-${{ steps.version-env.outputs.sha_short }}.apk
          mv app/build/outputs/apk/armv7/debug/*.apk app/build/outputs/apk/armv7/debug/snapenhance-${{ env.version }}-armv7-${{ steps.version-env.outputs.sha_short }}.apk
          mv app/build/outputs/apk/all/debug/*.apk app/build/outputs/apk/all/debug/snapenhance-${{ env.version }}-universal-${{ steps.version-env.outputs.sha_short }}.apk
      
      - name: Upload armv8
        uses: actions/upload-artifact@v3.1.2
        with:
          name: snapenhance-armv8-debug
          path: app/build/outputs/apk/armv8/debug/*

      - name: Upload armv7
        uses: actions/upload-artifact@v3.1.2
        with:
          name: snapenhance-armv7-debug
          path: app/build/outputs/apk/armv7/debug/*

      - name: Upload universal
        uses: actions/upload-artifact@v3.1.2
        with:
          name: snapenhance-universal-debug
          path: app/build/outputs/apk/all/debug/*

      - name: CI Upload armv8
        if:  ${{ inputs.ci_upload }} 
        run: node ./.github/workflows/upload.js -t "${{ secrets.TELEGRAM_BOT_TOKEN }}" -f "app/build/outputs/apk/armv8/debug/snapenhance-${{ env.version }}-armv8-${{ steps.version-env.outputs.sha_short }}.apk" --caption "A new commit has been pushed to the ${{ env.GIT_BRANCH_NAME }} branch! ${{ steps.version-env.outputs.sha_short }}" --chatid "${{ secrets.TELEGRAM_CHAT_ID }}" 

      - name: CI Upload armv7
        if:  ${{ inputs.ci_upload }} 
        run: node ./.github/workflows/upload.js -t "${{ secrets.TELEGRAM_BOT_TOKEN }}" -f "app/build/outputs/apk/armv7/debug/snapenhance-${{ env.version }}-armv7-${{ steps.version-env.outputs.sha_short }}.apk" --chatid "${{ secrets.TELEGRAM_CHAT_ID }}" 

      - name: CI Upload universal
        if:  ${{ inputs.ci_upload }} 
        run: node ./.github/workflows/upload.js -t "${{ secrets.TELEGRAM_BOT_TOKEN }}" -f "app/build/outputs/apk/all/debug/snapenhance-${{ env.version }}-universal-${{ steps.version-env.outputs.sha_short }}.apk" --chatid "${{ secrets.TELEGRAM_CHAT_ID }}" 
